---
# Source: xray/charts/mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-mongodb
  labels:
    app: mongodb
    chart: "mongodb-2.0.5"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  mongodb-root-password: "ekcxMEV1RzYwWg=="
  mongodb-password: "T2J2SHVETU9WbA=="
