---
# Source: xray/templates/xray-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: xray
    chart: xray-0.8.1
    release: "release-name"
    heritage: "Tiller"
  name: release-name-xray
subjects:
- kind: ServiceAccount
  name: release-name-xray
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: release-name-xray
