---
# Source: xray/templates/xray-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: xray
    chart: xray-0.8.1
    release: "release-name"
    heritage: "Tiller"
  name: release-name-xray
