---
# Source: xray/templates/xray-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: xray
    chart: xray-0.8.1
    release: "release-name"
    heritage: "Tiller"
  name: release-name-xray
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list

