---
# Source: xray/templates/xray-analysis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-xray-analysis
  labels:
    app: xray
    chart: xray-0.8.1
    component: xray-analysis
    heritage: Tiller
    release: release-name
spec:
  type: ClusterIP
  ports:
  - port: 7000
    protocol: TCP
    name: http
    targetPort: 7000
  selector:
    app: xray
    component: xray-analysis
    release: release-name