---
# Source: xray/charts/rabbitmq-ha/templates/rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: rabbitmq-ha
    chart: "rabbitmq-ha-1.9.1"
    release: "release-name"
    heritage: "Tiller"
  name: release-name-rabbitmq-ha
subjects:
  - kind: ServiceAccount
    name: release-name-rabbitmq-ha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-rabbitmq-ha
