---
# Source: xray/charts/rabbitmq-ha/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: rabbitmq-ha
    chart: "rabbitmq-ha-1.9.1"
    release: "release-name"
    heritage: "Tiller"
  name: release-name-rabbitmq-ha
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
