---
# Source: xray/charts/rabbitmq-ha/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: release-name-rabbitmq-ha
  labels:
    app: rabbitmq-ha
    chart: "rabbitmq-ha-1.9.1"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  rabbitmq-username: "Z3Vlc3Q="
  rabbitmq-password: "U0xvbGUzR3Z4Umg4bWxtZFpEdXJXUVlD"
  rabbitmq-erlang-cookie: "WFJBWVJBQkJJVE1RQ0xVU1RFUg=="
  definitions.json: "ewogICJ1c2VycyI6IFsKICAgIHsKICAgICAgIm5hbWUiOiAibWFuYWdlbWVudCIsCiAgICAgICJwYXNzd29yZCI6ICJFOVIzZmpabTRlakZrVkZFIiwKICAgICAgInRhZ3MiOiAibWFuYWdlbWVudCIKICAgIH0sCiAgICB7CiAgICAgICJuYW1lIjogImd1ZXN0IiwKICAgICAgInBhc3N3b3JkIjogIlNMb2xlM0d2eFJoOG1sbWRaRHVyV1FZQyIsCiAgICAgICJ0YWdzIjogImFkbWluaXN0cmF0b3IiCiAgICB9CiAgXSwKICAidmhvc3RzIjogWwogICAgewogICAgICAibmFtZSI6ICIvIgogICAgfQogIF0sCiAgInBlcm1pc3Npb25zIjogWwogICAgewogICAgICAidXNlciI6ICJndWVzdCIsCiAgICAgICJ2aG9zdCI6ICIvIiwKICAgICAgImNvbmZpZ3VyZSI6ICIuKiIsCiAgICAgICJyZWFkIjogIi4qIiwKICAgICAgIndyaXRlIjogIi4qIgogICAgfQogIF0sCiAgInBvbGljaWVzIjogWwogICAgewogICAgICAibmFtZSI6ICJoYS1hbGwiLAogICAgICAiYXBwbHktdG8iOiAiYWxsIiwKICAgICAgInBhdHRlcm4iOiAiLioiLAogICAgICAidmhvc3QiOiAiLyIsCiAgICAgICJkZWZpbml0aW9uIjogewogICAgICAgICJoYS1tb2RlIjogImFsbCIsCiAgICAgICAgImhhLXN5bmMtbW9kZSI6ICJhdXRvbWF0aWMiLAogICAgICB9CiAgICB9CiAgXQp9"

