---
# Source: xray/charts/rabbitmq-ha/templates/service-discovery.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-rabbitmq-ha-discovery
  labels:
    app: rabbitmq-ha
    chart: rabbitmq-ha-1.9.1
    release: release-name
    heritage: Tiller
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: http
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: 4369
      targetPort: epmd
  selector:
    app: rabbitmq-ha
    release: release-name
  type: ClusterIP
