---
# Source: xray/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql
  labels:
    app: release-name-postgresql
    chart: "postgresql-0.9.5"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  
  postgres-password: "M0pZWnVIcGx0bg=="
  
